### ISSUE TITLE
Figure out inkscape+latex or tikz, and pick a final document type that looks good

### ISSUE THREAD

**Issue by katyhuff** [arfc/2019-richter-msr-fc#2]
Figure out inkscape+latex or tikz, and pick a final document type that looks good. 
This issue can be closed when an inscape+latex version and a tikz version have been made and compared.

**Comment by ZoeRichter** [comment]
The branch issue2 currently has an inkscape-generated svg file that has been converted to .pdf_tex, and successfully included in the msr-list report.  A tikz test is in progress

**Comment by ZoeRichter** [comment]
Issue 2 has both graph versions, and there is a pull request for this issue

**Comment by andrewryh** [comment]
@ZoeRichter Checkout `graphviz`: https://www.graphviz.org/

Simple visualization: http://graphviz.it, http://www.webgraphviz.com/

**Comment by ZoeRichter** [comment]
With the use of graphviz, this issue can be closed.
